name: regardless_site
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.3.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.1+1
  google_fonts: ^6.2.0
  loading_indicator: ^3.1.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.14
  lottie: ^3.1.3
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.1.0
  simple_gradient_text: 1.3.0
  intl: ^0.19.0
  flutter_widget_from_html_core: ^0.15.2
  font_awesome_flutter: ^10.4.0
  visibility_detector: ^0.4.0+2
  flutter_linkify: ^6.0.0
  flutter_faq: ^1.0.1+1
  firebase_core_web: ^2.18.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^5.4.4
  dart_mappable: ^4.2.2
  fluttertoast: ^8.2.8


dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  dart_mappable_builder: ^4.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/